from fastapi import APIRouter, HTTPException, BackgroundTasks
from pydantic import BaseModel
from typing import Optional
from app.core.security import CurrentUser
from app.db.supabase import get_supabase
from app.agents.support_workflow import support_app

router = APIRouter()

class SupportTicketCreate(BaseModel):
    query_text: str
    category: Optional[str] = None
    organization_id: str

async def async_trigger_support_agent(ticket_id: str, organization_id: str, query_text: str, category: Optional[str]):
    initial_state = {
        "ticket_id": ticket_id,
        "organization_id": organization_id,
        "query_text": query_text,
        "category": category,
        "semantic_results": [],
        "draft_reply": "",
        "status": "processing"
    }
    await support_app.ainvoke(initial_state)

@router.post("/")
async def create_ticket(ticket: SupportTicketCreate, user: CurrentUser, background_tasks: BackgroundTasks):
    """
    Creates a new support ticket.
    This acts as Trigger 2: Self-Healing Desk, triggering the LangGraph agent
    to query Weaviate and attempt a resolution automatically.
    """
    supabase = get_supabase()
    data = {
        "organization_id": ticket.organization_id,
        "query_text": ticket.query_text,
        "category": ticket.category,
        "resolution_status": "open"
    }
    
    response = supabase.table("support_tickets").insert(data).execute()
    if getattr(response, 'data', None):
        ticket_id = response.data[0]["id"]
        
        # Trigger Agent in background to query Weaviate and resolve
        background_tasks.add_task(
            async_trigger_support_agent, 
            ticket_id=ticket_id, 
            organization_id=ticket.organization_id, 
            query_text=ticket.query_text, 
            category=ticket.category
        )
        return {"message": "Ticket created and processing started", "ticket_id": ticket_id}
        
    raise HTTPException(status_code=500, detail="Failed to create support ticket")

@router.get("/{ticket_id}")
async def get_ticket_status(ticket_id: str, user: CurrentUser):
    """
    Returns the resolution generated by the AI agent for a specific ticket.
    """
    supabase = get_supabase()
    response = supabase.table("support_tickets").select("resolution_status, resolution_text, query_text").eq("id", ticket_id).execute()
    
    if getattr(response, 'data', None) and len(response.data) > 0:
        ticket = response.data[0]
        return {
            "message": "Ticket status", 
            "status": ticket.get("resolution_status"),
            "resolution": ticket.get("resolution_text"),
            "query": ticket.get("query_text")
        }
        
    raise HTTPException(status_code=404, detail="Ticket not found")
